table FactPrioritySensitivity
	lineageTag: 64a430b4-a1dc-4d66-9785-5699351e612f

	column Scenario
		dataType: string
		lineageTag: 67f35305-6e9e-4af1-a26d-d2352f7a98cb
		summarizeBy: none
		sourceColumn: Scenario

		annotation SummarizationSetBy = Automatic

	column 'CHSA Code'
		dataType: string
		lineageTag: 60b34dad-06d6-41fc-920c-b1428e4d02c9
		summarizeBy: none
		sourceColumn: CHSA Code

		annotation SummarizationSetBy = Automatic

	column 'CHSA Name'
		dataType: string
		lineageTag: 82c3311c-21ab-4b54-8e06-597be4af74a8
		summarizeBy: none
		sourceColumn: CHSA Name

		annotation SummarizationSetBy = Automatic

	column 'Priority Score'
		dataType: double
		formatString: 0.00
		lineageTag: 99352126-ad0e-47cb-9b9f-d520f8e6a5fd
		summarizeBy: sum
		sourceColumn: Priority Score

		annotation SummarizationSetBy = Automatic

	column 'Priority Rank'
		dataType: int64
		formatString: 0
		lineageTag: 0f935162-94e5-4c0f-bfe5-d1132c8541f8
		summarizeBy: min
		sourceColumn: Priority Rank

		annotation SummarizationSetBy = Automatic

	column 'Spearman versus Balanced'
		dataType: double
		formatString: 0.000
		lineageTag: f09f1b70-49e5-4a98-a17e-200d80c854c2
		summarizeBy: min
		sourceColumn: Spearman versus Balanced

		annotation SummarizationSetBy = Automatic

	partition FactPrioritySensitivity = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(pProjectRoot & "\outputs\analytical\sensitivity_analysis.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				    Select = Table.SelectColumns(Headers,{"Scenario","CHSA_Code","CHSA_Name","PriorityScore","PriorityRank","SpearmanVsBalanced"}),
				    Rename = Table.RenameColumns(Select,{{"CHSA_Code","CHSA Code"},{"CHSA_Name","CHSA Name"},{"PriorityScore","Priority Score"},{"PriorityRank","Priority Rank"},{"SpearmanVsBalanced","Spearman versus Balanced"}}),
				    Typed = Table.TransformColumnTypes(Rename,{{"Scenario",type text},{"CHSA Code",type text},{"CHSA Name",type text},{"Priority Score",type number},{"Priority Rank",Int64.Type},{"Spearman versus Balanced",type number}})
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

